# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b798f26cada53fee3f4e2d8c620e4cae7f92d360d989d220832cedba3a4ad910a7358e55a4391ea93ca34388cb28c0fbd1380655dfd4b5a6d7a94d04a19a25c7

test:
  secret_key_base: 7ddea3259468ed3ed79c133f070c9a83e4ad339c352371fad5ccc83464f28eec670c1afc91ac95928228a45e356cb6cd30d409750541e059c709e360c625a409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
